name: main

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"

jobs:

  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        osm: [v0.2.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.1.0
        with:
          version: ${{ matrix.osm }}
          command: osm version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        run: shellcheck bin/*
